### ISSUE TITLE
Add Bulk Data Export Operation 

### ISSUE THREAD

**Issue by fheuschkel** [samply/blaze#210] opened 2020-09-16 12:13 UTC
This issue is part of the huge issue ["Implement Bulk Data Export #158"](https://github.com/samply/blaze/issues/158)
This Issue just includes Task creation, but not execution!

Add module operation-bulk-data-export with handlers for `$export` and `$__export-status`. 
Include as optional feature.

`$export`:
- check parameters and validate request.
- create task resource.
- return response 202 with content location or error.

`$__export-status`:
- if [base]/Task/ID/$__export-status is requested, return In-Progress response.

**Comment by alexanderkiel** [comment] 2023-07-20 07:12
Duplicate of #158

**Closed by alexanderkiel** 2023-07-20 07:12 UTC
